version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: interview-manager-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-interview_manager}
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - interview-manager-network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER:-postgres}']
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: interview-manager-redis
    ports:
      - '6379:6379'
    networks:
      - interview-manager-network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile.production
    container_name: interview-manager-server
    env_file:
      - .env
    ports:
      - '3000:3000'
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - interview-manager-network
    volumes:
      - uploads:/app/uploads
    command: >
      sh -c "apk add --no-cache ffmpeg &&
             npm run start:prod"

volumes:
  postgres_data:
  uploads:

networks:
  interview-manager-network:
    driver: bridge
